#!/bin/bash

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP INTALL DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

#ynh_backup "/etc/fail2ban/jail.d/$app.conf"
#ynh_backup "/etc/fail2ban/filter.d/$app.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/var/log/$app"

#=================================================
# BACKUP MYSQL DATABASE
#=================================================
ynh_print_info "Backing up database..."

ynh_mysql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script complete. YunoHost will now copy those files to the archive."
