#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
email=$(ynh_user_get_info --username="$admin" --key=mail)

#timezone=$(timedatectl show --value --property=Timezone)

#admin_pass=$(ynh_string_random --length=24)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
#ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=email --value="$email"

#ynh_app_setting_set --key=admin_pass --value=$admin_pass

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#chmod -R 775 "$install_dir"
#chmod -R o-rwx "$install_dir"
#chown -R "$app" "$install_dir"
mkdir -p $install_dir/wp-content/uploads
mkdir -p $install_dir/wp-content/temp
chown -R $app:www-data "$install_dir"
find "$install_dir" -type d -exec chmod 750 {} \;
find "$install_dir" -type f -exec chmod 640 {} \;
find "$install_dir/wp-content/uploads" -type d -exec chmod 770 {} \;
find "$install_dir/wp-content/temp" -type d -exec chmod 770 {} \;
setfacl -Rm d:g:www-data:rwX "$install_dir/wp-content/uploads"
setfacl -Rm d:g:www-data:rwX "$install_dir/wp-content/temp"

dir=__DIR__

ynh_config_add --template="wp-config.php" --destination="$install_dir/wp-config.php"

for i in 1 2 3 4 5 6 7 8
do
	j=$(ynh_string_random --length=40)
	ynh_replace --match="KEY$i" --replace="$j" --file=$install_dir/wp-config.php
	sleep 0.5
done

ynh_replace --match="The password you chose during installation." --replace="[your YunoHost account password]" --file=$install_dir/wp-admin/includes/upgrade.php

#ynh_config_add --template="composer.json" --destination="$install_dir/composer.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#touch "/var/log/$app/$app.log"
#chmod 660 "/var/log/$app/$app.log"
#chown "$app:www-data" "/var/log/$app/$app.log"

#ynh_config_add_fail2ban --logpath="/var/log/$app/auth.log" --failregex="Authentication (attempt for unknown user|failure for) .* from <HOST>"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Install $app..."

ynh_local_curl "/wp-admin/install.php?step=2" "&weblog_title=$admin%20$app%20blog" "user_name=$admin" "admin_password=$db_pwd" "admin_password2=$db_pwd" "admin_email=$email" "Submit=Install%20ClassicPress"

#=================================================
# INSTALL WORDPRESS PLUGINS
#=================================================
ynh_script_progression "Installing $app plugins..."

ynh_hide_warnings wget --no-verbose https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --output-document=$install_dir/wp-cli.phar
wpcli_alias="php$php_version $install_dir/wp-cli.phar --allow-root --path=$install_dir"

$wpcli_alias plugin install authldap
$wpcli_alias plugin install companion-auto-update
#$wpcli_alias plugin install wp-fail2ban-redux

#=================================================
# SET LANGUAGE
#=================================================
ynh_script_progression "Configuring language..."

$wpcli_alias core language install $language
$wpcli_alias site switch-language $language

#=================================================
# CONFIGURE LDAP
#=================================================
db_prefix="cp_"
ynh_replace --match="__DB_PREFIX__" --replace="$db_prefix" --file=../conf/ldap.sql
ynh_replace --match="__APP__" --replace="$app" --file=../conf/ldap.sql
ynh_replace --match="__LENGTH__" --replace="$((${#app} + 108))" --file=../conf/ldap.sql
ynh_mysql_db_shell < ../conf/ldap.sql

#=================================================
# ACTIVATE WORDPRESS PLUGINS
#=================================================
ynh_script_progression "Activating plugins..."

$wpcli_alias plugin activate authldap
$wpcli_alias plugin activate companion-auto-update
#$wpcli_alias plugin activate wp-fail2ban-redux

#=================================================
# REMOVE WP-CLI.PHAR
#=================================================
ynh_safe_rm $install_dir/wp-cli.phar

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app complete."
